version: '3.3'
services:
  mysql:
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - 3306
      - 33060
    networks:
      - my_network
    volumes:
     - 'data:/var/lib/mysql'
    image: mysql
  
  wordpress:
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpressdb
    ports:
      - '80:80'
    networks:
      - my_network
    volumes:
      - 'wp_data:/var/www/html'
    image: wordpress
networks:
  my_network:
volumes:
  data:
  wp_data:
