version: "3.8"
services:
    mongo:
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=max
            - MONGO_INITDB_ROOT_PASSWORD=secret
        volumes:
            - data:/data/db
        image: mongo
        networks:
            - shoopinglist-network
    backend:
        ports:
            - 80:80
        volumes:
            - logs:/logs
            - node_modules:/node_modules
        image: murtadoc/shoppinglist-backend   
        networks:
            - shoopinglist-network     
    frontend:
        ports:
            - 3000:3000
        volumes:
            - ./frontend/src:/src
        image: murtadoc/shoppinglist-frontend
        networks:
            - shoopinglist-network
networks:
    shoopinglist-network:
volumes:
    data:
    logs:
    node_modules:
