global:
  scrape_interval: 15s # Scrape the target every 15 seconds
  evaluation_interval: 15s 

rule_files:
  - alert-rules-exam.yml # alert rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093 

scrape_configs:
  - job_name: "backbox"
    metrics_path: /probe
    static_configs:
      - targets: 
        - http://shoppinglist-alwa.azurewebsites.net/ # the deployed app
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

